#! /bin/sh

# PATH setup
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/bin:$PATH"

# Locale
export LANG=en_US.UTF-8
export LANGUAGE=en
export LC_ADDRESS=es_CL.UTF-8
export LC_ALL=
export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_IDENTIFICATION=es_CL.UTF-8
export LC_MEASUREMENT=es_CL.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=es_CL.UTF-8
export LC_NAME=es_CL.UTF-8
export LC_NUMERIC=es_CL.UTF-8
export LC_PAPER=es_CL.UTF-8
export LC_TELEPHONE=es_CL.UTF-8
export LC_TIME=es_CL.UTF-8

# Program settings
export BLOCK_SIZE="human-readable"
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export LESS=' m - R '
export PAGER=less
export TIME_STYLE=$(printf "%s\n%s" "+%e %b  %Y" "%e %b %R")
export QT_QPA_PLATFORMTHEME=gnome
export EDITOR=$(
    command -v emacsclient ||
    command -v emacs       ||
    command -v nano        ||
    command -v ed
)
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Source bash config for bash login shells
if [ -n "${BASH_VERSION}" ] && [ -f "${HOME}/.bashrc" ]; then
    . "${HOME}/.bashrc"
fi

# Local host overrides
if [ -f "${HOME}/.profile.local" ]; then
    . "${HOME}/.profile.local"
fi
