[ids]
*

[main]
; bind to something not used elsewhere
capslock = hangeul
shift+capslock = compose
compose = rightmeta
rightalt = leftalt
9 = 9
0 = 0
[ = (
] = )
; = :

[shift]
9 = [
0 = ]
[ = {
] = }
; = ;
